title: Elena Sierra
description: AI for Sustainability and Social Good
baseurl: "" # Leave blank unless your site is in a subdirectory
url: "https://yourusername.github.io" # Update with your actual GitHub Pages URL

# Markdown and theme settings
markdown: kramdown
theme: minima # Or any supported Jekyll theme
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
